### ISSUE TITLE
Real trading

### ISSUE THREAD

**Issue by micasa001** [tiagosiebler/TriangularArbitrage#15]
We now have the complete basic settings to start real trades. Optimization, AI etc. is the next job but there is a moment you have to step into the big world of trading :) 

In the config we need a value; true/false for real trading to activate.

**How trading should work**

Based on the settings in the config the tool will start scanning.
- Based on the ranking of the best pairs a trade will be started with the maximum defined amount in the config.
- In the config should be defined how we buy/sell. As we have 2 options:

1. Sell/buy strategy =  Marketprice: the tool see an opportunity and buy and sell the pairs always for the Marketprice. Risk is that the prices will change but we will never stay with dust.

2. Sell/buy strategy = Limitprice: the tool calculate the maximum buy price and minimal sell price for each pair and place limit orders. This will ensure we always sell for the price we need to make profit as calculated in the arbitrage. Risk; prices can change and we can't sell the coins anymore.

IN CASE 2 WE NEED THE NEXT TRADING SOLUTION

a. We wait 5 minutes (make time dynamic in config) to see if the price change and the opportunity come back.
b. After wait time the scanner will start finding arbitrage opportunities for the failed coin. The arbitrage loop should end again at the failed coin: 

example; we start A-B-C-A. But the process fails at B. Now the scan should start looking to opportunities to B-C-A-B. 

Reason for this setup: as we can define the coins we like to trade with we only buy coins that we already would buy ourself. In the worst case we end with more coins than that we started.

**Comment by wwarlock** [comment]
Hi guys.
Is here any enchantments are planning or maybe realized already?

**Comment by tiagosiebler** [comment]
See "contributions" here:
https://github.com/tiagosiebler/TriangularArbitrage#contributions
