### ISSUE TITLE
Auto trade

### ISSUE THREAD

**Issue by ArtjomIV** [tiagosiebler/TriangularArbitrage#20]
I see that it shows great arbitrage opportunities. Does it have functionality to auto trade because only bot can react so fast. A found that there is a config already for auto trading (docs/brainstorm/config.md)?.

**Comment by tiagosiebler** [comment]
Hello @ArtjomIV, not yet. Right now it's using the bid price for every step, which isn't the right approach (#21). Once that's sorted, I'll start looking at paper trading to see how feasible this is even with slight artificial delays before using the market price. It's still in really early phases but you're welcome to help out if you're interested in contributing.
