### ISSUE TITLE
Issue when launching

### ISSUE THREAD

**Issue by TalhaA** [tiagosiebler/TriangularArbitrage#45]
Sorry for this nb question. Probably something that I've missed during the installation of MongoDB but any help will be appreciated.
I get the following error:
[npm-debug.log](https://github.com/tiagosiebler/TriangularArbitrage/files/1670720/npm-debug.log)

/Users/HoneyGuide1/TriangularArbitrage/index.js:71
require('./lib/DBCore')(logger, (err, db)=>{
                                         ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! TriangularArbitrage@0.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TriangularArbitrage@0.2.0 start script 'node index.js'.
npm ERR! This is most likely a problem with the TriangularArbitrage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls TriangularArbitrage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/HoneyGuide1/TriangularArbitrage/npm-debug.log

**Comment by tiagosiebler** [comment]
Hello, an estimated guess is that you're on an older version of NodeJS. Your node environment doesn't seem to understand the arrow function expression.
