### ISSUE TITLE
it is not understood how it works

### ISSUE THREAD

**Issue by vandaloz** [tiagosiebler/TriangularArbitrage#48]
Hello, can someone explain to me how would be the operation in vase to the table that is displayed after running npm star?. We buy B and immediately change it to C?, And at what price do we buy B and C ?, and when we have already bought C what do we do? We change by BTC ?? if so, do not count the commissions to go from C to BTC ?? .. Please someone to put a short description of how it would be a full arbitrage operation with this program based on the table shown when we run the program. Thank you very much.

**Comment by tiagosiebler** [comment]
The numbers you see are based on live prices on the exchange, assuming you buy/sell at each step at the current orders. This project only looks for live opportunities based on each pair's orderbook, it's only built for monitoring at this time, while recording and outputting the top results.

A finished triangular arbitrage bot could further monitor the orderbook to check for volume at those prices, and place trades to make use of the opportunities if the orderbook volume allows it. Contributions are most welcome.
