### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by caoyu1988** [tiagosiebler/TriangularArbitrage#56]
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 31.13.68.1:9443
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TriangularArbitrage@0.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TriangularArbitrage@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-11-07T02_56_51_375Z-debug.log

**Comment by tiagosiebler** [comment]
Network error, timeout trying to reach "31.13.68.1:9443". Most likely a proxy blocking your request?

**Comment by jimoquinn** [comment]
Follow up note.  When I received the same error it was caused by a firewall blocking my outgoing connection from TriangularArbitrage when it attempted to connect to Binance on port 9443.

**Comment by tiagosiebler** [comment]
Thanks!
