### ISSUE TITLE
TypeError: exchange.WS.onAllTickerStream is not a function

### ISSUE THREAD

**Issue by TwatKnight** [tiagosiebler/TriangularArbitrage#60]
Hi, I've been getting this error, not sure how to solve it. Any ideas?

TypeError: exchange.WS.onAllTickerStream is not a function
at Object.CurrencyCore.startAllTickerStream (/home/test/TriangularArbitrage/lib/CurrencyCore.js:342:60)
at CurrencyCore.init (/home/test/TriangularArbitrage/lib/CurrencyCore.js:21:16)
at module.exports (/home/test/TriangularArbitrage/lib/BotCore.js:41:48)
at /home/test/TriangularArbitrage/index.js:86:27
at DBCore.startupDB (/home/test/TriangularArbitrage/lib/DBCore.js:5:12)
at Object. (/home/test/TriangularArbitrage/index.js:71:24)
at Module._compile (internal/modules/cjs/loader.js:1123:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
at Module.load (internal/modules/cjs/loader.js:972:32)
at Function.Module._load (internal/modules/cjs/loader.js:872:14)

**Comment by TAKXInvest** [comment]
The script itself is out of date. The binance API was changed a few months ago.

**Comment by TAKXInvest** [comment]
The editor did a good job at the start, even if there were some calculation errors.

It is not an arbitration bot, just a tool to display opportunities.
I modified it to become one, and frankly it works pretty well, but don't expect the Jackpot;

**Comment by TwatKnight** [comment]
I see, that's unfortunate. I just wanted to use it like how you described it, a tool to display opportunities.

**Comment by TAKXInvest** [comment]
I just tested, in "testmod" mode it displays the information well.

Good .. They are false, but the script still works.

![Capture](https://user-images.githubusercontent.com/44720280/80184495-fb2c4980-860a-11ea-905d-3d6200ecd9ab.JPG)

**Comment by TAKXInvest** [comment]
> In " conf.ini " -> useMongo=**false**

> In Files " .keys-template " rename to **" .keys "**

> Use NodeJS Lasted version

> npm install
> npm start

And it's Good :)

**Comment by tiagosiebler** [comment]
> The editor did a good job at the start, even if there were some calculation errors.
> 
> It is not an arbitration bot, just a tool to display opportunities.
> I modified it to become one, and frankly it works pretty well, but don't expect the Jackpot;

I've not dabbled with this project for a while, but if you have improvements you wish to contribute for demonstrative purposes, I'll happily review any pull requests. Even if just for the "displaying opportunities" aspect of this.

**Comment by TAKXInvest** [comment]
I will see to extract the calculation system for you.
The bot part, it bothers me a bit to share it freely, because after many tests, it is for single use.

Two people using the bot has the effect of cutting profits in half, which is not "top".
![Capture](https://user-images.githubusercontent.com/44720280/80185470-ad184580-860c-11ea-8364-aea16acca1de.JPG)

We changed it well, and you did a great job at the start. "Respect".

I'm going to see the improvements for you and send this to you.

**Comment by tiagosiebler** [comment]
> I will see to extract the calculation system for you.
> The bot part, it bothers me a bit to share it freely, because after many tests, it is for single use.
> 
> Two people using the bot has the effect of cutting profits in half, which is not "top".
> ![Capture](https://user-images.githubusercontent.com/44720280/80185470-ad184580-860c-11ea-8364-aea16acca1de.JPG)
> 
> We changed it well, and you did a great job at the start. "Respect".
> 
> I'm going to see the improvements for you and send this to you.

Thanks TAKX, I totally understand about sharing the trading part of this - you don't have to share that, for obvious reasons. My suggestion was purely on the display part of this where you've found things that were broken or outdated and have quick contributions to add, so others can still use this as a learning tool or for displaying the state of these tickers. 

Hope this has helped you make some profits either way!

**Comment by TwatKnight** [comment]
> > In " conf.ini " -> useMongo=**false**
> 
> > In Files " .keys-template " rename to **" .keys "**
> 
> > Use NodeJS Lasted version
> 
> > npm install
> > npm start
> 
> And it's Good :)

Already tried this on 3 different machines(Two are on Ubuntu 16.04.06, and on a Win10 64bit) and I still get the same error. 

NodeJS version is 12.6.2, also tried it on 14.0.0, still the same error.

**Comment by daryl552007** [comment]
I am having the same issue with  TwatKnight .

@TAKXInvest can you share to us that version you modified that is working?

thanks

**Comment by avaxtasulta** [comment]
Same problem here. @TAKXInvest could you possibly give us the modified files without the bot module?

**Comment by fvsgit** [comment]
Same issue here

**Comment by tiagosiebler** [comment]
Better late than never! Fixed the onAllTickerStream error and stripped some old logic out.

**Comment by avaxtasulta** [comment]
@tiagosiebler thanks :) works like a charm now! going to spend the day using my complete lack of coding skills to try figure out how to automatically place trades on the top result haha. if anyone can help with some code snippets to copy and paste it would be much appreciated! cheers again for your work :)

**Comment by tiagosiebler** [comment]
> @tiagosiebler thanks :) works like a charm now! going to spend the day using my complete lack of coding skills to try figure out how to automatically place trades on the top result haha. if anyone can help with some code snippets to copy and paste it would be much appreciated! cheers again for your work :)

best way to learn and improve! Just be careful, the math definitely needs a review so caution is definitely advised. This uses the "all symbols" tickers for bid/ask prices, so there may also be a tiny amount of lag between real price and what the ticker says.
